// <auto-generated />
using System;
using Back.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Back.Data.Migrations
{
    [DbContext(typeof(BancoDBContext))]
    [Migration("20240304181727_Versao_04.00")]
    partial class Versao_0400
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Back.Dominio.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Integer");

                    b.Property<string>("Cliente")
                        .HasMaxLength(255);

                    b.Property<int>("Dia")
                        .HasColumnType("Int");

                    b.Property<string>("Email")
                        .HasMaxLength(255);

                    b.Property<string>("HoraCron")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("Porta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasDefaultValue(0);

                    b.Property<string>("SMTP")
                        .HasMaxLength(255);

                    b.Property<string>("Senha")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("CONFIGURACOES");
                });

            modelBuilder.Entity("Back.Dominio.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Integer");

                    b.Property<string>("AreaPath");

                    b.Property<string>("NomeUsuario")
                        .HasMaxLength(255);

                    b.Property<bool>("Principal")
                        .HasColumnType("Bit");

                    b.Property<string>("ProjetoId")
                        .HasMaxLength(255);

                    b.Property<string>("ProjetoNome")
                        .HasMaxLength(255);

                    b.Property<string>("Sprint")
                        .HasMaxLength(255);

                    b.Property<string>("TimeId")
                        .HasMaxLength(255);

                    b.Property<string>("TimeNome")
                        .HasMaxLength(255);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UrlCorporacao")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("CONTAS");
                });

            modelBuilder.Entity("Back.Dominio.Models.Sincronizar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Integer");

                    b.Property<DateTime?>("DataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("DateTime");

                    b.Property<int>("Status")
                        .HasColumnType("Int");

                    b.HasKey("Id");

                    b.ToTable("SINCRONIZACOES");
                });
#pragma warning restore 612, 618
        }
    }
}
